apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api-pricing
  name: api-pricing
spec:
  ports:
    - name: "5070"
      port: 5070
      targetPort: 5070
  selector:
    io.kompose.service: api-pricing
status:
  loadBalancer: {}
