apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api-clusters
  name: api-clusters
spec:
  ports:
    - name: "4070"
      port: 4070
      targetPort: 4070
  selector:
    io.kompose.service: api-clusters
status:
  loadBalancer: {}
