apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api-catalog
  name: api-catalog
spec:
  ports:
    - name: "6070"
      port: 6070
      targetPort: 6070
  selector:
    io.kompose.service: api-catalog
status:
  loadBalancer: {}
